Added another workflow action job for testing the public usage of the action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,3 +23,21 @@ jobs:
         run: |
           ls -al
           test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
+
+  test_job_2:
+    runs-on: ubuntu-latest
+    name: Test job for redoc-cli GitHub Action
+    steps:
+      # To use this repository's private action, you must check out the repository
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: redoc-cli test
+        uses: seeebiii/redoc-cli-github-action
+        with:
+          args: 'bundle test/petstore.yml -o petstore.html'
+
+      - name: check result
+        run: |
+          ls -al
+          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
